//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book_A_Majig_v2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookingModelContainer : DbContext
    {
        public BookingModelContainer()
            : base("name=BookingModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<AccessLevel> AccessLevels { get; set; }
        public virtual DbSet<BookingNotes> BookingNotes { get; set; }
        public virtual DbSet<BookingClasification> BookingClasifications { get; set; }
        public virtual DbSet<BookingConfirmation> BookingConfirmations { get; set; }
        public virtual DbSet<Restaurant> Restaurants { get; set; }
        public virtual DbSet<LockOutDate> LockOutDates { get; set; }
        public virtual DbSet<LockOutTime> LockOutTimes { get; set; }
    }
}
