//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book_A_Majig_v2
{
    using System;
    using System.Collections.Generic;
    
    public partial class LockOutDate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LockOutDate()
        {
            this.BookingClasifications = new HashSet<BookingClasification>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Reason { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int RestaurantId { get; set; }
    
        public virtual LockOutTime LockOutTime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingClasification> BookingClasifications { get; set; }
        public virtual AccessLevel AccessLevel { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
