//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book_A_Majig_v2.DatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingNote
    {
        public int Id { get; set; }
        public string Note { get; set; }
        public int Booking_Id { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<System.DateTime> DateInactive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public int Severity { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
