//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book_A_Majig_v2.DatabaseEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccessLevel> AccessLevels { get; set; }
        public virtual DbSet<BookingClasification> BookingClasifications { get; set; }
        public virtual DbSet<BookingConfirmation> BookingConfirmations { get; set; }
        public virtual DbSet<BookingNote> BookingNotes { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<LockOutDate> LockOutDates { get; set; }
        public virtual DbSet<LockOutTime> LockOutTimes { get; set; }
        public virtual DbSet<Restaurant> Restaurants { get; set; }
        public virtual DbSet<PresetNote> PresetNotes { get; set; }
        public virtual DbSet<EmployeeAvailabilityDay> EmployeeAvailabilityDays { get; set; }
        public virtual DbSet<EmployeeNA> EmployeeNAs { get; set; }
        public virtual DbSet<Shift> Shifts { get; set; }
        public virtual DbSet<EmployeeShift> EmployeeShifts { get; set; }
        public virtual DbSet<EmployeeAvailabilityHoursRequest> EmployeeAvailabilityHoursRequests { get; set; }
        public virtual DbSet<Permissions> Permissions { get; set; }
        public virtual DbSet<Roster> Rosters { get; set; }
        public virtual DbSet<EmployeeCommendation> EmployeeCommendations { get; set; }
        public virtual DbSet<EmployeeCommendationClassification> EmployeeCommendationClassifications { get; set; }
        public virtual DbSet<EmployeeLevelCategory> EmployeeLevelCategories { get; set; }
        public virtual DbSet<EmployeeShiftPresets> EmployeeShiftPresets { get; set; }
        public virtual DbSet<ShiftCategory> ShiftCategories { get; set; }
    }
}
