//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book_A_Majig_v2.DatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DateNote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DateNote()
        {
            this.AppearOnAddingBooking = true;
            this.AppearOnRoster = true;
        }
    
        public int Id { get; set; }
        public System.DateTime StartDate { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> InactiveDate { get; set; }
        public bool AppearOnAddingBooking { get; set; }
        public bool AppearOnRoster { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
    }
}
