//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book_A_Majig_v2.DatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeCommendationClassification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeCommendationClassification()
        {
            this.TeamCommendations = new HashSet<TeamCommendation>();
            this.EmployeeCommendationSkillCategories = new HashSet<EmployeeCommendationSkillCategory>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Weighting { get; set; }
        public bool AvailableOnTeam { get; set; }
        public bool AvailableOnUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamCommendation> TeamCommendations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeCommendationSkillCategory> EmployeeCommendationSkillCategories { get; set; }
    }
}
