//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book_A_Majig_v2.DatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeCommendation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeCommendation()
        {
            this.RecievingEmployee = new HashSet<Employee>();
        }
    
        public int Id { get; set; }
        public string Notes { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> RecievingEmployee { get; set; }
        public virtual Shift Shift { get; set; }
        public virtual EmployeeCommendationClassification EmployeeCommendationClassification { get; set; }
        public virtual Employee CommendedBy { get; set; }
    }
}
